databases:
  - name: emma-s
    databaseName: emma_s
    user: emma_s_user

services:
  - type: web
    name: budget-expens1
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://emma_s_user:eSF2XIBn8pAhQbpm9SrRVSvIxyOmrtmO@dpg-ciiqe9lgkuvojjcrqqug-a.oregon-postgres.render.com/emma_s
        fromDatabase:
          name: emma_s
          property: connectionString
      - key: bc5f4695b80732cb07d4ec9932fd181b
        sync: false